{{- if .Values.kepler.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # Creates a unique name for the binding based on your release
  name: {{ .Release.Name }}-kepler-privileged-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    # Dynamically matches the ServiceAccount name Kepler generates
    name: {{ .Release.Name }}-kepler
    namespace: {{ .Release.Namespace }}
{{- end }}
